title = "EdAnisko.com"
baseURL = "https://edanisko.com"
canonifyurls=true
languageCode = "en-us"
theme = "ananke"

disqusShortname = "edanisko"
disable_share = false

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = 'EdAnisko.com'
    weight = 1
    
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-R3HHRTR66H"
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  site_logo = ""
  description = "Without a Net."
  facebook = "https://www.facebook.com/edanisko"
  twitter = "https://twitter.com/edanisko"
  instagram = ""
  youtube = ""
  github = "https://github.com/edanisko"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/ed-anisko/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "https://edanisko.com/index.xml"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "/images/rsz_jesus-kiteque-wn-kyahwcis-unsplash.jpg"
  recent_posts_number = 4
  
  


[markup.goldmark.renderer]
  unsafe = true